---
- name: create bash config
  template:
    src: gentoo/etc/profile.d/lua.sh.j2
    dest: /etc/profile.d/lua.sh
    owner: root
    group: root
    mode: 0644

- name: install packages
  portage:
    name: "{{ item }}"
    getbinpkg: yes
    quiet: yes
  with_items:
    - dev-lua/luaossl
    - app-crypt/laprassl

- name: install lua packages
  luarocks:
    name: lapis
    state: present

- name: create ca config
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: nginx
    group: nginx
    mode: 0640
  with_items:
    - { src: "gentoo/etc/laprassl/config.lua.j2", dest: "/etc/laprassl/config.lua" }
  notify:
    - restart nginx

- name: bootstrap ca
  shell: "lua /usr/share/webapps/laprassl/9999/bootstrap.lua"
  args:
    creates: "/var/lib/laprassl/{{ inventory_hostname }}.crt.pem"
    chdir: "/usr/share/webapps/laprassl/9999"

- name: create nginx config
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - { src: "gentoo/etc/nginx/conf.d/laprassl.conf.j2", dest: "/etc/nginx/conf.d/laprassl.conf" }
  notify:
    - restart nginx
