---
- name: create bash config
  template:
    src: gentoo/etc/profile.d/lua.sh.j2
    dest: /etc/profile.d/lua.sh
    owner: root
    group: root
    mode: 0644

- name: install packages
  portage:
    name: "{{ item }}"
    getbinpkg: yes
    quiet: yes
  with_items:
    - dev-python/requests
    - dev-python/cryptography
    - dev-lua/luaossl
    - dev-lua/luarocks
    - app-crypt/laprassl

- name: install lua packages
  luarocks:
    name: lapis
    state: present

- name: create ssl group
  group:
    name: ssl
    system: yes
    state: present

- name: loop laprassl configuration
  include: ssl.yml
  until: laprasslCaFile.stat.exists == True
  retries: 2
