---
- include: buildbot.yml
- include: dom0.yml
- include: git.yml
- include: lxd.yml
- include: nginx.yml
- include: rabbitmq.yml
- include: redis.yml
- include: rsync.yml
- include: slapd.yml
- include: phpldapadmin.yml
- include: phpmyadmin.yml
- include: postgresql.yml
- include: mariadb.yml
- include: bind.yml
- include: dhcpd.yml
