---
- name: install packages
  portage:
    name: "{{ item }}"
    quiet: yes
    getbinpkg: yes
  with_items:
    - dev-db/postgresql
    - dev-python/psycopg

- name: stat /var/lib/postgresql/9.5
  stat:
    path: /var/lib/postgresql/9.5
  register: postgresqlInitialized

- name: enable unattanded configuration
  lineinfile:
    dest: /etc/conf.d/postgresql-9.5
    regexp: '^correct=true$'
    line: 'correct=true'
    state: present
  when: postgresqlInitialized.stat.exists == False

- name: create database
  command: emerge --config dev-db/postgresql
  args:
    creates: /var/lib/postgresql/9.5

- name: clear unattaneded configuration
  lineinfile:
    dest: /etc/conf.d/postgresql-9.5
    regexp: '^correct=true$'
    line: 'correct=true'
    state: absent

- name: create config
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: postgres
    group: postgres
    mode: 0600
  with_items:
    - { src: gentoo/etc/postgresql-9.5/postgresql.conf.j2, dest: /etc/postgresql-9.5/postgresql.conf }
    - { src: gentoo/etc/postgresql-9.5/pg_hba.conf.j2, dest: /etc/postgresql-9.5/pg_hba.conf }
  notify:
    - reload postgresql

- name: create initscript symlinks
  file:
    src: /etc/init.d/postgresql-9.5
    dest: /etc/runlevels/default/postgresql-9.5
    state: link

- name: start initscript
  service:
    name: postgresql-9.5
    state: started

- name: set postgres password
  command: psql -U postgres -c "ALTER USER postgres WITH PASSWORD '{{ postgresqlConfig['password'] }}';"
  changed_when: false

- name: create databases
  postgresql_db:
    name: "{{ item['name'] }}"
  with_items: "{{ (postgresqlConfig | default([]))['user'] | default([]) }}"

- name: create user
  postgresql_user:
    name: "{{ item['name'] }}"
    db: "{{ item['name'] }}"
    password: "{{ item['password'] }}"
    priv: ALL
  with_items: "{{ (postgresqlConfig | default([]))['user'] | default([]) }}"

- name: set database ownership
  postgresql_db:
    name: "{{ item['name'] }}"
    owner: "{{ item['name'] }}"
  with_items: "{{ (postgresqlConfig | default([]))['user'] | default([]) }}"
