---
- name: "create zone directory {{ zoneItem }}"
  file:
    dest: "/etc/icinga2/zones.d/{{ zoneItem }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: "create zone hosts.conf {{ zoneItem }}"
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: gentoo/etc/icinga2/zones.d/hosts.conf.j2, dest: "/etc/icinga2/zones.d/{{ zoneItem }}/hosts.conf" }
