---
- name: install packages
  portage:
    name: "{{ item }}"
    getbinpkg: yes
    quiet: yes
    state: present
  with_items:
    - www-apps/icingaweb2

- name: create nginx config
  template:
    src: gentoo/etc/nginx/conf.d/icingaweb.conf.j2
    dest: /etc/nginx/conf.d/icingaweb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: create /etc/icingaweb2
  file:
    dest: /etc/icingaweb2
    owner: root
    group: icingaweb2
    mode: '2770'
    state: directory

- name: add nobody to icingaweb2 group
  user:
    name: nobody
    groups: icingaweb2
  notify:
    - restart php-fpm
    - restart nginx

- name: create ldap config
  template:
    src: gentoo/etc/openldap/ldap.conf.j2
    dest: /etc/openldap/ldap.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart php-fpm
