---
# comment

- name: create /var/lib/lxc/{{ lxcItem.split('.')[0] }}/rootfs
  file:
    dest: /var/lib/lxc/{{ lxcItem.split('.')[0] }}/rootfs
    state: directory

- name: copy lxc config of {{ lxcItem }}
  template:
    src: var/lib/lxc/config.j2
    dest: "/var/lib/lxc/{{ lxcItem.split('.')[0] }}/config"
    owner: root
    group: root
    mode: 0600

- name: create container {{ lxcItem }}
  lxc_container:
    name: "{{ lxcItem.split('.')[0] }}"
    config: "/var/lib/lxc/{{ lxcItem.split('.')[0] }}/config"
    directory: "/var/lib/lxc/{{ lxcItem.split('.')[0] }}/rootfs"
    container_command: /sbin/init
    container_log: True
    template: gentoo-overlay
    template_options: "--iface={{ hostvars[lxcItem]['lxcConfig']['interface'] | default('eth0') }} --iaddr={{ hostvars[lxcItem]['lxcConfig']['ipv4addr'] | default('dhcp') }} --route={{ hostvars[lxcItem]['lxcConfig']['ipv4route'] | default('default') }}"
    state: started

- name: link initscript of {{ lxcItem }}
  file:
    src: /etc/init.d/lxc
    dest: "/etc/init.d/lxc.{{ lxcItem.split('.')[0] }}"
    state: link

- name: link initscript of {{ lxcItem }} to runlevel
  file:
    src: "/etc/init.d/lxc.{{ lxcItem.split('.')[0] }}"
    dest: "/etc/runlevels/default/lxc.{{ lxcItem.split('.')[0] }}"
    force: True
    state: link
