---
- name: install package
  portage:
    name: "{{ item }}"
    getbinpkg: yes
    quiet: yes
  with_items:
    - dev-vcs/git
    - dev-util/buildbot-slave

- name: link initscript
  file:
    src: /etc/init.d/buildslave
    dest: /etc/runlevels/default/buildslave
    state: link

- name: update user
  user:
    name: buildbot
    home: /var/lib/buildslave

- name: update ssh config
  ssh_config:
    user: "{{ item.user }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { user: "{{ buildConfig['user'] | default('buildbot') }}", option: StrictHostKeyChecking, value: 'no' }
    - { user: "{{ buildConfig['user'] | default('buildbot') }}", option: IdentityFile, value: '~/.ssh/build.key' }

- name: copy private key
  copy:
    content: "{{ authConfig['sshKey'] }}"
    dest: "{{ buildConfig['user'] | default('buildbot') | getHome }}/.ssh/build.key"
    owner: "{{ buildConfig['user'] | default('buildbot') }}"
    group: "{{ buildConfig['user'] | default('buildbot') }}"
    mode: 0600

- name: create data directory
  file:
    dest: /var/lib/buildslave
    owner: "{{ buildConfig['user'] | default('buildbot') }}"
    group: "{{ buildConfig['group'] | default('buildbot') }}"
    mode: 0750
    state: directory

- name: create buildslave
  command: "buildslave create-slave /var/lib/buildslave {{ buildConfig['master'] }}:9989 {{ buildConfig['name'] }} {{ buildConfig['password'] }}"
  args:
    creates: /var/lib/buildslave/info
  register: buildCreate

- name: update permissions
  file:
    dest: /var/lib/buildslave
    owner: "{{ buildConfig['user'] | default('buildbot') }}"
    group: "{{ buildConfig['group'] | default('buildbot') }}"
    recurse: yes
  when: buildCreate.changed

- name: update metadata
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ buildConfig['user'] | default('buildbot') }}"
    group: "{{ buildConfig['group'] | default('buildbot') }}"
    mode: 0640
  with_items:
    - { src: var/lib/buildslave/info/admin.j2, dest: /var/lib/buildslave/info/admin }
    - { src: var/lib/buildslave/info/host.j2, dest: /var/lib/buildslave/info/host }
  notify:
    - restart buildslave

- name: update config
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { dest: /var/lib/buildslave/buildbot.tac, regexp: '^slavename = .*', line: "slavename = '{{ buildConfig['name'] }}'" }
    - { dest: /var/lib/buildslave/buildbot.tac, regexp: '^passwd = .*', line: "passwd = '{{ buildConfig['password'] }}'" }
    - { dest: /etc/conf.d/buildslave, regexp: '^USERNAME=".*"', line: "USERNAME=\"{{ buildConfig['user'] | default('buildbot') }}\"" }
  notify:
    - restart buildslave

- name: set python default version
  command: eselect python set 1

- name: start service
  service:
    name: buildslave
    state: started
