---
- name: "create csr config {{ cfsslRootItem['name'] }}"
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: cfssl
    group: cfssl
    mode: 0640
  with_items:
    - { src: "gentoo/etc/cfssl/csr/ca.json.j2", dest: "/etc/cfssl/csr/{{ cfsslRootItem['name'] }}.json" }

- name: "create rootCA {{ cfsslRootItem['name'] }}"
  shell: "cfssl gencert -initca '/etc/cfssl/csr/{{ cfsslRootItem['name'] }}.json' | cfssljson -bare '{{ cfsslRootItem['name'] }}'"
  args:
    creates: "/var/lib/cfssl/{{ cfsslRootItem['name'] }}.pem"
    chdir: /var/lib/cfssl

- name: loop all sub CA certificates
  include: subca.yml
  loop_control:
    loop_var: cfsslSubItem
  with_items: "{{ (cfsslRootItem | default({}))['child'] | default([]) }}"
