---
- name: create csr config
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: cfssl
    group: cfssl
    mode: 0640
  with_items:
    - { src: "gentoo/etc/cfssl/csr/ca.json.j2", dest: "/etc/cfssl/csr/{{ cfsslSubItem['name'] }}.json" }

- name: "create subCA {{ cfsslSubItem['name'] }}"
  shell: "cfssl gencert -initca /etc/cfssl/csr/'{{ cfsslSubItem['name'] }}.json' | cfssljson -bare '{{ cfsslSubItem['name'] }}'"
  args:
    creates: "/var/lib/cfssl/{{ cfsslSubItem['name'] }}.pem"
    chdir: /var/lib/cfssl

- name: "sign subCA {{ cfsslSubItem['name'] }}"
  shell: "cfssl sign -ca '{{ cfsslRootItem['name'] }}.pem' -ca-key '{{ cfsslRootItem['name'] }}-key.pem' -config '/etc/cfssl/config.json' -profile subca '{{ cfsslSubItem['name'] }}.csr' | cfssljson -bare '{{ cfsslSubItem['name'] }}'"
  args:
    creates: "/var/lib/cfssl/{{ cfsslSubItem['name'] }}.pem"
    chdir: /var/lib/cfssl
