---
# gentoo common config

- name: update network config
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { 'src': etc/conf.d/hostname.j2, 'dest': /etc/conf.d/hostname }
    - { 'src': etc/conf.d/net.j2, 'dest': /etc/conf.d/net }

- name: symlink network interfaces
  file:
    src: net.lo
    dest: "/etc/init.d/net.{{ item.key }}"
    state: link
  with_dict: "{{ hostvars[inventory_hostname]['hostConfig']['network']['interfaces'] }}"

- name: enable all network interfaces
  file:
    src: "/etc/init.d/net.{{ item.key }}"
    dest: "/etc/runlevels/default/net.{{ item.key }}"
    state: link
  with_dict: "{{ hostvars[inventory_hostname]['hostConfig']['network']['interfaces'] }}"

- name: start all network interfaces
  service:
    name: "net.{{ item.key }}"
    state: started
  with_dict: "{{ hostvars[inventory_hostname]['hostConfig']['network']['interfaces'] }}"

- name: create /etc/portage/repos.conf
  file:
    dest: /etc/portage/repos.conf
    state: directory

- name: configure portage repositories
  copy:
    src: etc/portage/repos.conf/overlay.conf
    dest: /etc/portage/repos.conf/overlay.conf
    owner: root
    group: root
    mode: 0644

- name: update portage
  portage:
    sync: yes
  when: "'lxc' not in group_names"

- name: create /usr/portage/distfiles and /usr/portage/packages
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - /usr/portage/distfiles
    - /usr/portage/packages

- name: set portage profile
  file:
    src: /usr/local/fnordpipe-overlay/profiles/amd64/headless
    dest: /etc/portage/make.profile
    force: yes
    state: link

- name: install base packages
  portage:
    name: "{{ item }}"
    quiet: yes
    getbinpkg: yes
    state: present
  with_items:
    - app-admin/syslog-ng
    - net-misc/curl

- name: link initscripts
  file:
    src: /etc/init.d/syslog-ng
    dest: /etc/runlevels/default/syslog-ng
    state: link

- name: start syslog
  service:
    name: syslog-ng
    state: started
