---
# gentoo common config

- name: update network config
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { 'src': etc/conf.d/hostname.j2, 'dest': /etc/conf.d/hostname }
    - { 'src': etc/conf.d/net.j2, 'dest': /etc/conf.d/net }
  when: inventory_hostname not in groups['dom0']

- name: create /etc/portage/repos.conf
  file:
    dest: /etc/portage/repos.conf
    state: directory

- name: configure portage repositories
  copy:
    src: etc/portage/repos.conf/overlay.conf
    dest: /etc/portage/repos.conf/overlay.conf
    owner: root
    group: root
    mode: 0644

- name: update portage
  portage:
    sync: yes
  when: "'lxc' not in group_names"

- name: create /usr/portage/distfiles and /usr/portage/packages
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - /usr/portage/distfiles
    - /usr/portage/packages

- name: set portage profile
  file:
    src: /usr/local/fnordpipe-overlay/profiles/amd64/headless
    dest: /etc/portage/make.profile
    force: yes
    state: link

- name: install base packages
  portage:
    name: net-misc/curl
    quiet: yes
    getbinpkg: yes
    state: present
