---
- name: install packages
  portage:
    name: "{{ item }}"
    quiet: yes
    getbinpkg: yes
  with_items:
    - net-nds/phpldapadmin

- name: copy phpldapadmin config
  template:
    src: gentoo/usr/share/webapps/phpldapadmin/1.2.3-r1/htdocs/config/config.php.j2
    dest: /usr/share/webapps/phpldapadmin/1.2.3-r1/htdocs/config/config.php
    owner: root
    group: root
    mode: 0644

- name: copy nginx config
  template:
    src: gentoo/etc/nginx/conf.d/phpldapadmin.conf.j2
    dest: /etc/nginx/conf.d/phpldapadmin.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - restart nginx
