---
- name: create certificate file
  shell: "cat {{ inventory_hostname }}.pem rootca.pem > /etc/ssl/{{ inventory_hostname }}-nginx.pem"
  args:
    chdir: /var/lib/cfssl
  when: sslHostCert.changed == True
  notify:
    - restart nginx

- name: update permissions
  file:
    dest: "{{ item['dest'] }}"
    owner: "{{ item['owner'] }}"
    group: "{{ item['group'] }}"
    recurse: "{{ item['recurse'] }}"
    state: "{{ item['state'] }}"
  with_items:
    - { dest: "/etc/ssl/{{ inventory_hostname }}-nginx.pem", owner: nginx, group: nginx, recurse: no, state: file }
    - { dest: "/etc/ssl/{{ inventory_hostname }}-key.pem", owner: nginx, group: nginx, recurse: no, state: file }
    - { dest: "/etc/ssl/{{ inventory_hostname }}-dh.pem", owner: nginx, group: nginx, recurse: no, state: file }
