---
- name: install packages
  portage:
    name: "{{ item }}"
    quiet: yes
    getbinpkg: yes
    state: present
  with_items:
    - net-misc/rabbitmq-server

- name: create config
  template:
    src: "{{ item['src']}}"
    dest: "{{ item['dest'] }}"
    owner: rabbitmq
    group: rabbitmq
    mode: 0644
  with_items:
    - { src: 'gentoo/etc/rabbitmq/rabbitmq-env.conf.j2', dest: '/etc/rabbitmq/rabbitmq-env.conf' }
    - { src: 'gentoo/etc/rabbitmq/rabbitmq.config.j2', dest: '/etc/rabbitmq/rabbitmq.config' }
  notify:
    - restart rabbitmq

- name: create nginx config
  template:
    src: gentoo/etc/nginx/conf.d/rabbitmq.conf.j2
    dest: /etc/nginx/conf.d/rabbitmq.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - restart nginx

- name: create initscript symlink
  file:
    src: /etc/init.d/rabbitmq
    dest: /etc/runlevels/default/rabbitmq
    state: link

- name: start initscript
  service:
    name: rabbitmq
    state: started

- name: enable management plugin
  command: rabbitmq-plugins enable rabbitmq_management
  register: rabbitmqPlugin
  changed_when: rabbitmqPlugin.stdout.find('nothing to do') == False
