---
# comment

- name: copy domU config of {{ domUItem }}
  template:
    src: etc/xen/config/domU.config.j2
    dest: /etc/xen/config/{{ domUItem.split('.')[0] }}.config
    owner: root
    group: root
    mode: 0600
  vars:
    domUMac: "{{ genericConfig.macprefix | default('de:ad:be:ef') }}:{{ domUItem | hash('md5') | regex_replace('^([0-9a-f]{2}).*([0-9a-f]{2})$', '\\1:\\2') }}"

- name: create logical volume of {{ domUItem }}
  lvol:
    vg: "{{ domUItem.split('.')[1] }}"
    lv: "{{ domUItem.split('.')[0] }}"
    size: 10g
    state: present

- name: create dom'U {{ domUItem }}
  xen_xl:
    config: /etc/xen/config/{{ domUItem.split('.')[0] }}.config
    name: "{{ domUItem.split('.')[0] }}"
    template: gentoo-overlay
    template_args: "--iface={{ hostvars[domUItem]['hostConfig']['network']['default'] | default('eth0') }}"
    state: started
