---
# dom0 setup

- include_vars:
    file: "{{ lookup('env','PLAYBOOK_VAULT_DIR') }}/config.yml"
    name: genericConfig

- name: create /etc/xen/config
  file:
    dest: /etc/xen/config
    owner: root
    group: root
    mode: 0750
    state: directory

- name: loop dom0 group
  include: domU/main.yml
  with_items: "{{ groups['dom0'] }}"
  loop_control:
    loop_var: dom0Item
