---
- name: install packages
  portage:
    name: "{{ item }}"
    getbinpkg: yes
    quiet: yes
  with_items:
    - dev-python/redis-py
    - app-admin/ansible

- name: create directories
  file:
    dest: /etc/ansible
    owner: root
    group: root
    mode: 0755
    state: directory

- name: create config
  template:
    src: etc/ansible/ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: 0644
