---
- name: set timezone
  copy:
    remote_src: True
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    owner: root
    group: root
    mode: 0644

- name: create /root/.ssh
  file:
    dest: /root/.ssh
    owner: root
    group: root
    mode: 0700
    state: directory

- name: create /root/.ssh/authorized_keys
  copy:
    content: "{{ commonConfig['sshPubKey'] }}"
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600

- name: create /etc/conf.d/{hostname,net} and /etc/hosts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: gentoo/etc/hosts.j2, dest: /etc/hosts, owner: root, group: root, mode: '0644' }
    - { src: gentoo/etc/conf.d/hostname.j2, dest: /etc/conf.d/hostname, owner: root, group: root, mode: '0644' }
    - { src: gentoo/etc/conf.d/net.j2, dest: /etc/conf.d/net, owner: root, group: root, mode: '0644' }

- name: create /etc/resolv.conf
  template:
    src: gentoo/etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: commonConfig is defined and commonConfig['network']['interfaces'][commonConfig['network']['default']]['ipv4addr'] != 'dhcp'

- name: create portage directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { dest: /usr/portage/distfiles, owner: root, group: portage, mode: 775 }
    - { dest: /usr/portage/packages, owner: root, group: portage, mode: 775 }
  when: lxdConfig['bridge'] is not defined

- name: create directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { dest: /etc/portage/repos.conf, owner: root, group: root, mode: 755 }

- name: create /etc/portage/repos.conf/distro.conf
  template:
    src: gentoo/etc/portage/repos.conf/distro.conf.j2
    dest: /etc/portage/repos.conf/distro.conf
    owner: root
    group: root
    mode: 0644
  when: commonConfig['gentoo']['main-repo'] is defined and commonConfig['gentoo']['repos'] is defined

- name: create /etc/portage/make.profile
  file:
    src: "{{ commonConfig['gentoo']['profile'] }}"
    dest: /etc/portage/make.profile
    force: yes
    state: link
  when: commonConfig['gentoo']['profile'] is defined

- name: install default packages
  portage:
    name: "{{ item }}"
    getbinpkg: yes
    quiet: yes
    state: present
  with_items:
    - net-misc/bridge-utils
    - app-admin/syslog-ng
    - net-misc/curl

- name: create network initscripts
  file:
    src: net.lo
    dest: "/etc/init.d/net.{{ item.key }}"
    state: link
  with_dict: "{{ commonConfig['network']['interfaces'] }}"

- name: link network initscripts
  file:
    src: "/etc/init.d/net.{{ item.key }}"
    dest: "/etc/runlevels/default/net.{{ item.key }}"
    state: link
  with_dict: "{{ commonConfig['network']['interfaces'] }}"

- name: link initscripts
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: /etc/init.d/sshd, dest: /etc/runlevels/default/sshd }
    - { src: /etc/init.d/syslog-ng, dest: /etc/runlevels/default/syslog-ng }

- name: start network services
  service:
    name: net.{{ item.key }}
    state: started
  with_dict: "{{ commonConfig['network']['interfaces'] }}"

- name: start services
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - sshd
    - syslog-ng
