---
- name: install packages
  portage:
    name: "{{ item }}"
    getbinpkg: yes
    quiet: yes
    state: present
  with_items:
    - dev-python/requests

- name: create ssl group
  group:
    name: ssl
    system: yes
    state: present

- name: create dhparam
  shell: "openssl dhparam -out /etc/ssl/{{ inventory_hostname }}-dh.pem 4096"
  args:
    creates: "/etc/ssl/{{ inventory_hostname }}-dh.pem"

- name: update dh permissions
  file:
    dest: "/etc/ssl/{{ inventory_hostname }}-dh.pem"
    owner: root
    group: ssl
    mode: 0640
    state: file

- name: create host certificate
  laprassl:
    crt: "/etc/ssl/{{ inventory_hostname }}.crt.pem"
    key: "/etc/ssl/{{ inventory_hostname }}.key.pem"
    ca: /etc/ssl/ca.crt.pem
    authkey: "{{ sslConfig['authkey'] }}"
    subject: "CN={{ inventory_hostname }}, C={{ sslConfig['C'] }}, L={{ sslConfig['L'] }}, ST={{ sslConfig['ST'] }}, O={{ sslConfig['O'] }}, OU={{ sslConfig['OU'] }}"
    profile: "{{ sslConfig['profile'] }}"
    url: "https://{{ sslConfig['url'] }}"
    owner: root
    group: ssl
    mode: 0640
  when:
    - inventory_hostname not in groups['laprassl']
