---
- name: install packages
  portage:
    name: "{{ item }}"
    getbinpkg: yes
    quiet: yes
  with_items:
    - dev-vcs/git
    - dev-util/buildbot

- name: update user
  user:
    name: buildbot
    home: /var/lib/buildmaster

- name: create directories
  file:
    dest: "{{ item.dest }}"
    owner: buildbot
    group: buildbot
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - { dest: "/var/lib/buildmaster/{{ buildConfig['name'] }}", mode: 750 }
    - { dest: "/var/lib/buildmaster/.ssh", mode: 700 }

- name: update ssh config
  lineinfile:
    dest: "/var/lib/buildmaster/.ssh/config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: buildbot
    group: buildbot
    mode: 0600
    state: present
    create: yes
  with_items:
    - { regexp: '^StrictHostKeyChecking .*$', line: StrictHostKeyChecking no }
    - { regexp: '^IdentityFile .*$', line: IdentityFile ~/.ssh/build.key }

- name: copy private key
  copy:
    content: "{{ authConfig['sshKey'] }}"
    dest: "/var/lib/buildmaster/.ssh/build.key"
    owner: buildbot
    group: buildbot
    mode: 0600

- name: create master
  command: "buildbot create-master /var/lib/buildmaster/{{ buildConfig['name'] }}"
  args:
    creates: "/var/lib/buildmaster/{{ buildConfig['name'] }}/buildbot.tac"
  register: buildCreate

- name: update permissions
  file:
    dest: "/var/lib/buildmaster/{{ buildConfig['name'] }}"
    owner: buildbot
    group: buildbot
    recurse: yes
  when: buildCreate.changed

- name: create master.cfg
  template:
    src: var/lib/buildmaster/master.cfg.j2
    dest: /var/lib/buildmaster/{{ buildConfig['name'] }}/master.cfg
    owner: buildbot
    group: buildbot
    mode: 0640

- name: create initscript symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: buildmaster, dest: "/etc/init.d/buildmaster.{{ buildConfig['name'] }}" }
    - { src: "/etc/init.d/buildmaster.{{ buildConfig['name'] }}", dest: "/etc/runlevels/default/buildmaster.{{ buildConfig['name'] }}" }

- name: start buildmaster
  service:
    name: "buildmaster.{{ buildConfig['name'] }}"
    state: started
