---
- name: install packages
  portage:
    name: dev-util/buildbot
    getbinpkg: yes
    quiet: yes

- name: create data directory
  file:
    dest: "/var/lib/buildmaster/{{ buildConfig['name'] }}"
    owner: buildbot
    group: buildbot
    mode: 0750
    state: directory

- name: create master
  command: "buildbot create-master /var/lib/buildmaster/{{ buildConfig['name'] }}"
  args:
    creates: "/var/lib/buildmaster/{{ buildConfig['name'] }}/buildbot.tac"

- name: update permissions
  file:
    dest: "/var/lib/buildmaster/{{ buildConfig['name'] }}"
    owner: buildbot
    group: buildbot
    recurse: yes

- name: create master.cfg
  template:
    src: var/lib/buildmaster/master.cfg.j2
    dest: /var/lib/buildmaster/{{ buildConfig['name'] }}/master.cfg
    owner: buildbot
    group: buildbot
    mode: 0640

- name: create initscript symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: buildmaster, dest: "/etc/init.d/buildmaster.{{ buildConfig['name'] }}" }
    - { src: "/etc/init.d/buildmaster.{{ buildConfig['name'] }}", dest: "/etc/runlevels/default/buildmaster.{{ buildConfig['name'] }}" }

- name: start buildmaster
  service:
    name: "buildmaster.{{ buildConfig['name'] }}"
    state: started
