---
- name: install packages
  portage:
    name: "{{ item }}"
    getbinpkg: yes
    quiet: yes
  with_items:
    - dev-vcs/git
    - dev-util/buildbot

- name: update user
  user:
    name: buildbot
    home: /var/lib/buildmaster

- name: update ssh config
  ssh_config:
    user: "{{ item.user }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { user: buildbot, option: StrictHostKeyChecking, value: 'no' }
    - { user: buildbot, option: IdentityFile, value: '~/.ssh/build.key' }

- name: copy private key
  copy:
    content: "{{ authConfig['sshKey'] }}"
    dest: "/var/lib/buildmaster/.ssh/build.key"
    owner: buildbot
    group: buildbot
    mode: 0600

- name: create data directory
  file:
    dest: "/var/lib/buildmaster/{{ buildConfig['name'] }}"
    owner: buildbot
    group: buildbot
    mode: 0750
    state: directory

- name: create master
  command: "buildbot create-master /var/lib/buildmaster/{{ buildConfig['name'] }}"
  args:
    creates: "/var/lib/buildmaster/{{ buildConfig['name'] }}/buildbot.tac"

- name: update permissions
  file:
    dest: "/var/lib/buildmaster/{{ buildConfig['name'] }}"
    owner: buildbot
    group: buildbot
    recurse: yes

- name: create master.cfg
  template:
    src: var/lib/buildmaster/master.cfg.j2
    dest: /var/lib/buildmaster/{{ buildConfig['name'] }}/master.cfg
    owner: buildbot
    group: buildbot
    mode: 0640

- name: create initscript symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: buildmaster, dest: "/etc/init.d/buildmaster.{{ buildConfig['name'] }}" }
    - { src: "/etc/init.d/buildmaster.{{ buildConfig['name'] }}", dest: "/etc/runlevels/default/buildmaster.{{ buildConfig['name'] }}" }

- name: start buildmaster
  service:
    name: "buildmaster.{{ buildConfig['name'] }}"
    state: started
