---
- name: install dhcpd
  portage:
    package: "{{ item }}"
    quiet: yes
    getbinpkg: yes
    state: present
  with_items:
    - net-misc/dhcp
    - net-dns/bind-tools

- name: set interface for dhcpd
  lineinfile:
    dest: /etc/conf.d/dhcpd
    regexp: '(# )?DHCPD_IFACE=".*"'
    line: DHCPD_IFACE="{{ dhcpdConfig['interface'] }}"

- name: update dhcpd config
  template:
    src: gentoo/etc/dhcp/dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dhcpd

- name: start initscript
  service:
    name: dhcpd
    enabled: yes
    state: started

- name: create nsupdate script
  template:
    src: gentoo/etc/dhcp/dhcp.nsupdate.j2
    dest: /etc/dhcp/dhcp.nsupdate
    owner: root
    group: root
    mode: 0600

- name: create record for {{ inventory_hostname }} 
  command: "nsupdate -v -y hmac-md5:ddns-key:{{ dhcpdConfig['ddns-key'] }} /etc/dhcp/dhcp.nsupdate"
  changed_when: false
