---
# common server setup

- name: create /root/.ssh
  file:
    dest: /root/.ssh
    owner: root
    group: root
    mode: 0700
    state: directory

- name: update authorized_keys
  copy:
    content: "{{ genericConfig['sshPubKey'] }}"
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600

- name: enable sshd
  service:
    name: sshd
    state: started
    enabled: yes
