---
# common server setup

- name: create /root/.ssh
  file:
    dest: /root/.ssh
    owner: root
    group: root
    mode: 0700
    state: directory

- name: update authorized_keys
  copy:
    content: "{{ genericConfig['sshPubKey'] }}"
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600

- name: enable sshd
  service:
    name: sshd
    state: started
    enabled: yes

- name: update /etc/hosts
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: update /etc/resolv.conf
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: hostConfig is defined and hostConfig['network']['interfaces'][hostConfig['network']['default']]['ipv4addr'] is defined
