---
# common server setup

- name: create /root/.ssh
  file:
    dest: /root/.ssh
    owner: root
    group: root
    mode: 0700
    state: directory

- name: update authorized_keys
  copy:
    src: "{{ envAnsibleVault }}/root/.ssh/authorized_keys"
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600
  vars:
    envAnsibleVault: "{{ lookup('env','PLAYBOOK_VAULT_DIR') }}/roles/common"
