---
- name: install packages
  portage:
    name: "{{ item }}"
    quiet: yes
    getbinpkg: yes
  with_items:
    - dev-vcs/git
    - www-misc/fcgiwrap
    - www-servers/spawn-fcgi
    - www-apps/cgit

- name: check config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: gentoo/etc/nginx/conf.d/cgit.conf.j2, dest: /etc/nginx/conf.d/cgit.conf, owner: root, group: root, mode: 644 }
    - { src: gentoo/etc/conf.d/spawn-fcgi.j2, dest: /etc/conf.d/spawn-fcgi.cgit, owner: root, group: root, mode: 644 }
    - { src: gentoo/etc/cgitrc.j2, dest: /etc/cgitrc, owner: root, group: root, mode: 644 }
  notify:
    - restart nginx

- name: set initscript symlink
  file:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
    state: link
  with_items:
    - { src: spawn-fcgi, dest: /etc/init.d/spawn-fcgi.cgit }
    - { src: /etc/init.d/spawn-fcgi.cgit, dest: /etc/runlevels/default/spawn-fcgi.cgit }

- name: check user
  user:
    createhome: yes
    home: /var/lib/git
    name: git
    shell: /usr/bin/git-shell
    state: present

- name: start http service
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - spawn-fcgi.cgit

- name: update authorized_keys
  authorized_key:
    user: git
    key: "{{ item }}"
    state: present
  with_items: "{{ gitConfig['sshPubKeys'] | default([]) }}"

- name: copy private key
  copy:
    content: "{{ authConfig['sshKey'] }}"
    dest: /var/lib/git/.ssh/mirror.key
    owner: git
    group: git
    mode: 0600
  when: authConfig is defined

- name: create ssh config
  lineinfile:
    dest: /var/lib/git/.ssh/config
    regexp: "{{ item['regexp'] }}"
    line: "{{ item['line'] }}"
    owner: git
    group: git
    mode: 0600
    state: present
    create: yes
  with_items:
    - { regexp: '^StrictHostKeyChecking .*$', line: StrictHostKeyChecking no }
    - { regexp: '^IdentityFile .*$', line: IdentityFile ~/.ssh/mirror.key }
  when: authConfig is defined

- name: create repo config
  include: repo.yml
  with_items: "{{ gitConfig['repos'] | default([]) }}"
  loop_control:
    loop_var: gitItem
