---
- name: create git category {{ gitItem['category'] }}
  file:
    dest: "/var/lib/git/{{ gitItem['category'] }}"
    owner: git
    group: git
    mode: 0755
    state: directory

- name: "create repository {{ gitItem['category'] }}/{{ gitItem['name'] }}.git"
  command: "git init --bare {{ gitItem['category'] }}/{{ gitItem['name'] }}.git"
  args:
    chdir: /var/lib/git
    creates: "/var/lib/git/{{ gitItem['category'] }}/{{ gitItem['name'] }}.git"

- name: "create repo config {{ gitItem['category'] }}/{{ gitItem['name'] }}.git"
  template:
    src: "gentoo/var/lib/git/cgitrc.j2"
    dest: "/var/lib/git/{{ gitItem['category'] }}/{{ gitItem['name'] }}.git/cgitrc"
    owner: git
    group: git
    mode: 0644

- name: "create post-receive hook {{ gitItem['category'] }}/{{ gitItem['name'] }}.git"
  template:
    src: gentoo/var/lib/git/hooks/post-receive.j2
    dest: "/var/lib/git/{{ gitItem['category'] }}/{{ gitItem['name'] }}.git/hooks/post-receive"
    owner: git
    group: git
    mode: 0744
  when: gitItem['mirrors'] is defined

- name: "update repo permissions {{ gitItem['category'] }}/{{ gitItem['name'] }}.git"
  file:
    dest: "/var/lib/git/{{ gitItem['category']}}"
    owner: git
    group: git
    recurse: yes
