---
- name: install packages
  portage:
    name: "{{ item }}"
    getbinpkg: yes
    quiet: yes
  with_items:
    - dev-vcs/git
    - dev-util/buildbot

- name: update user
  user:
    name: buildbot
    home: /var/lib/buildmaster

- name: create directories
  file:
    dest: "{{ item.dest }}"
    owner: buildbot
    group: buildbot
    mode: "{{ item.mode }}"
    state: directory
  vars:
    buildbotName: "{{ (buildbotConfig['master'] | default({}))['name'] | default('') }}"
  with_items:
    - { dest: "/var/lib/buildmaster/{{ buildbotName }}", mode: '0750' }
    - { dest: "/var/lib/buildmaster/.ssh", mode: '0700' }

- name: update ssh config
  lineinfile:
    dest: "/var/lib/buildmaster/.ssh/config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: buildbot
    group: buildbot
    mode: 0600
    state: present
    create: yes
  with_items:
    - { regexp: '^StrictHostKeyChecking .*$', line: StrictHostKeyChecking no }
    - { regexp: '^IdentityFile .*$', line: IdentityFile ~/.ssh/build.key }

- name: copy private key
  copy:
    content: "{{ authConfig['sshKey'] }}"
    dest: "/var/lib/buildmaster/.ssh/build.key"
    owner: buildbot
    group: buildbot
    mode: 0600

- name: create master
  command: "buildbot create-master /var/lib/buildmaster/{{ buildbotConfig['master']['name'] }}"
  args:
    creates: "/var/lib/buildmaster/{{ buildbotConfig['master']['name'] }}/buildbot.tac"
  register: buildbotCreate

- name: update permissions
  file:
    dest: "/var/lib/buildmaster/{{ buildbotConfig['master']['name'] }}"
    owner: buildbot
    group: buildbot
    recurse: yes
  when: buildbotCreate.changed

- name: create master.cfg
  template:
    src: gentoo/var/lib/buildmaster/master.cfg.j2
    dest: /var/lib/buildmaster/{{ buildbotConfig['master']['name'] }}/master.cfg
    owner: buildbot
    group: buildbot
    mode: 0640
  register: buildService

- name: create initscript symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  vars:
    buildbotName: "{{ (buildbotConfig['master'] | default({}))['name'] | default('') }}"
  with_items:
    - { src: buildmaster, dest: "/etc/init.d/buildmaster.{{ buildbotName }}" }
    - { src: "/etc/init.d/buildmaster.{{ buildbotName }}", dest: "/etc/runlevels/default/buildmaster.{{ buildbotName }}" }

- name: start buildmaster
  service:
    name: "buildmaster.{{ buildbotConfig['master']['name'] }}"
    state: started

- name: restart buildmaster
  service:
    name: "buildmaster.{{ buildbotConfig['master']['name'] }}"
    state: restarted
  when: buildService.changed
