---
- name: install packages
  portage:
    name: dev-util/buildbot-gentoo-env
    getbinpkg: yes
    quiet: yes

- name: update publisher config
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: yes
  with_items:
    - { dest: /etc/rsyncPublish.cfg, regexp: '^rsyncHost=.*$', line: "rsyncHost={{ buildConfig['rsyncHost'] }}" }
    - { dest: /etc/httpPublish.cfg, regexp: '^httpHost=.*$', line: "httpHost={{ buildConfig['httpHost'] }}" }
