---
- name: install packages
  portage:
    name: "{{ item }}"
    quiet: yes
    getbinpkg: yes
  with_items:
    - dev-db/phpmyadmin

- name: create config
  template:
    src: gentoo/usr/share/webapps/phpmyadmin/4.6.5.1/htdocs/config.inc.php.j2
    dest: /usr/share/webapps/phpmyadmin/4.6.5.1/htdocs/config.inc.php
    owner: root
    group: root
    mode: 0644

- name: copy nginx config
  template:
    src: gentoo/etc/nginx/conf.d/phpmyadmin.conf.j2
    dest: /etc/nginx/conf.d/phpmyadmin.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - restart nginx
